# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - develop

variables:
  artifactName: Luminis.EntityFrameworkCore.AuditLogging
stages:
- stage: Build
 
  jobs:
  - job: Build
    displayName: Build the package
    pool:
      vmImage: 'ubuntu-latest'

    variables:
      buildConfiguration: 'Release'
      buildPlatform: 'Any CPU'
      solution: '**/*.sln'

    steps:
    - task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: 5.x

    - task: gitversion/execute@0
      displayName: Determine Version
                                 
    - task: NuGetToolInstaller@1
                                  
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
                          
    - task: DotNetCoreCLI@2
      inputs:
        command: 'pack'
        packagesToPack: '**/*.csproj'
        configuration: '$(buildConfiguration)'
        versioningScheme: 'byEnvVar'
        versionEnvVar: 'GitVersion.NuGetVersionV2'

    - task: DotNetCoreCLI@2
      displayName: DotnetCore Test
      inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--collect:"Code Coverage"'

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: $(artifactName)
                                                