<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <Authors>Luminis Arnhem</Authors>
    <Company>Luminis Arnhem</Company>
    <Copyright>Copyright (c) Luminis Arnhem 2020-2025</Copyright>

    <AssemblyName>Luminis.EntityFrameworkCore.AuditLogging</AssemblyName>
    <RootNamespace>Luminis.EntityFrameworkCore.AuditLogging</RootNamespace>
    <Description>Package for AuditLogging with Entity Framework Core</Description>
    <PackageProjectUrl>https://github.com/Luminis-Arnhem/EntityFrameworkCore.AuditLogging/</PackageProjectUrl>
    <RepositoryUrl>https://github.com/Luminis-Arnhem/EntityFrameworkCore.AuditLogging/</RepositoryUrl>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseFile>LICENSE.TXT</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <Nullable>enable</Nullable>
    <Version>$(VersionPrefix)</Version>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net10.0|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net10.0|AnyCPU'">
    <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net10.0'">
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.1" />
  </ItemGroup>
 
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
 
  <ItemGroup>
    <None Include="LICENSE.TXT" Pack="true" PackagePath="$(PackageLicenseFile)">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
